Extensions:
  Teleports:
    Defaults:
      Wait: 0
    Enabled: false
  Economy:
    Sell/Buy_Rate: 1.5
    Enabled: false
  Worlds:
    Defaults:
      Enviroment: NORMAL
      Mode: SURVIVAL
      Difficulty: NORMAL
      PVP: true
      BlockSpawn:
      - Giant
      Game:
        Type: Spleef
        Teams:
          Number: 3
          Team1:
            Name: Blue
            MaxPlayers: 1
          Team2:
            Name: Red
            MaxPlayers: 1
          Team3:
            Name: Spectators
            MaxPlayers: 28
        MaxPlayers: 30
    Enabled: false
